config/routes.rb
Rails.application.routes.draw do

  resources :restaurants do
    collection do
      get 'search'
    end
      resources :reviews, except: [:show, :index]
    end

  get 'pages/about'

  get 'pages/contact'

  get 'pages/manhattan'

  get 'pages/fairfield'

  get 'pages/westchester'

  root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  mount_uploader :image, ImageUploader


  searchkick

  has_many :reviews

  validates :name, :address, :phone, :website, :image, presence: true
  validates :phone, format: { with: /\A\(\d{3}\) \d{3}-\d{4}\z/,
  message: "must be in the format (123) 456-7890" }
  validates :website, format: { with: /\Ahttps?:\/\/.*\z/,
  message: "must start with http:// or https://" }
  validates :address, format: { with: /\A\d+[^,]+,[^,]+, [A-Z]{2} \d{5}\z/,
  message: "must be in the format 350 Fifth Avenue, New York, NY 10118" }
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]


  def search
    if params[:search].present?
      @restaurants = Restaurant.search(params[:search])
    else
      @restaurants = Restaurant.all
    end
  end


  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @reviews = Review.where(restaurant_id: @restaurant.id).order("created_at DESC")
    if @reviews.blank?
      @avg_rating = 0
    else
    @avg_rating = @reviews.average(:rating).round(2)
   end
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone, :website, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_restaurant

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.restaurant_id = @restaurant.id

    respond_to do |format|
        if @review.save
          format.html { redirect_to @restaurant, notice: 'Review was successfully created.' }
          format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_bootstrap.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

app/views/layouts/_navbar.html (copy).erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="margin-left:-35%;margin-top:-5%"><%= image_tag "https://s3.amazonaws.com/esrplunchtime/empirestaterealtytrust.jpg" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li style="box-shadow: 0 4px 8px 0 rgba(172, 194, 116, 0.8), 0 6px 20px 0 rgba(0, 0, 0, 0.8)"><%= link_to 'Add New Restaurant', new_restaurant_path, class: "btn btn-link" %></li>
        <li></li>
      </ul>
      <%= form_tag search_restaurants_path, method: :get, class: "navbar-form navbar-right" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag  "Search", name: nil, class: "btn btn-default" %>
        </p>
        <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="margin-left:-35%;margin-top:-10%"><%= image_tag "https://s3.amazonaws.com/esrplunchtime/logo300x100.png" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li style="margin-right:80px;box-shadow: 0 4px 8px 0 rgba(172, 194, 116, 0.8), 0 6px 20px 0 rgba(0, 0, 0, 0.8)"><%= link_to 'Add New Restaurant', new_restaurant_path, class: "btn btn-link" %></li>
        <li style="height:52px;box-shadow: 0 4px 8px 0 rgba(172, 194, 116, 0.8), 0 6px 20px 0 rgba(0, 0, 0, 0.8)" class="dropdown "><a href="#" id="drop1" data-toggle="dropdown" class="dropdown-toggle" role="button">Near Me<b class="caret"></b></a>
            <ul role="menu" class="dropdown-menu" aria-labelledby="drop1">
                <li role="presentation"><a href="/pages/manhattan" role="menuitem">Manhattan</a></li>
                <li role="presentation"><a href="/pages/fairfield" role="menuitem">Fairfield County</a></li>
                <li role="presentation"><a href="/pages/westchester" role="menuitem">Westchester County</a></li>
            </ul>
        </li>
      </ul>
      <%= form_tag search_restaurants_path, method: :get, class: "navbar-form navbar-right" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag  "Search", name: nil, class: "btn btn-default" %>
        </p>
        <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<script>
$(function(){
$(".dropdown").hover(
        function() {
            $('.dropdown-menu', this).stop( true, true ).fadeIn("fast");
            $(this).toggleClass('open');
            $('b', this).toggleClass("caret caret-up");
        },
        function() {
            $('.dropdown-menu', this).stop( true, true ).fadeOut("fast");
            $(this).toggleClass('open');
            $('b', this).toggleClass("caret caret-up");
        });
});
</script>

app/views/pages/contact.html.erb
<h1>We would love to hear from you!</h1>
<p>Contact us at restaurant@gmail.com</p>

app/views/pages/fairfield.html.erb
<a href="/pages/fairfield"></a>

<div class="row">
  <div class="col-md-8">
  <input id="pac-input" class="controls" type="text" placeholder="Search Box">
  <div id="map"></div>
  <script>
    function initAutocomplete() {
      var map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: 41.044626, lng: -73.548682},
        zoom: 14,
        mapTypeId: 'roadmap'
      });


      var input = document.getElementById('pac-input');
      var searchBox = new google.maps.places.SearchBox(input);
      map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

      map.addListener('bounds_changed', function() {
        searchBox.setBounds(map.getBounds());
      });

      var markers = [];

      searchBox.addListener('places_changed', function() {
        var places = searchBox.getPlaces();

        if (places.length == 0) {
          return;
        }


        markers.forEach(function(marker) {
          marker.setMap(null);
        });
        markers = [];


        var bounds = new google.maps.LatLngBounds();
        places.forEach(function(place) {
          if (!place.geometry) {
            console.log("Returned place contains no geometry");
            return;
          }
          var icon = {
            url: place.icon,
            size: new google.maps.Size(71, 71),
            origin: new google.maps.Point(0, 0),
            anchor: new google.maps.Point(17, 34),
            scaledSize: new google.maps.Size(25, 25)
          };

          markers.push(new google.maps.Marker({
            map: map,
            icon: icon,
            title: place.name,
            position: place.geometry.location
          }));

          if (place.geometry.viewport) {

            bounds.union(place.geometry.viewport);
          } else {
            bounds.extend(place.geometry.location);
          }
        });
        map.fitBounds(bounds);
      });
    }

  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAINDFMDvbITIo5__B3SmyEGa9kgplsUGU&libraries=places&callback=initAutocomplete"
       async defer></script>
     </div>
     <div class="col-md-4">
       <mark style="background:rgba(115,163,38,0.6)!important;font-size: 24px;box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.8), 0 6px 20px 0 rgba(0, 0, 0, 0.8);margin-left: 37%">Recommended</mark>
     <% if @reviews.blank? %>
       <h3></h3>
     <% else %>
     <table class="table" style="box-shadow: 0 4px 8px 0 rgba(172, 194, 116, 0.8), 0 6px 20px 0 rgba(0, 0, 0, 0.8)">
       <tbody>
         <% @restaurants.each do |restaurant| %>
           <tr>
             <td>
               <%= restaurant.name %>
              <%= restaurant.address %>
              <%= restaurant.phone %>
             <%= restaurant.website %>
             </td>
           </tr>
         <% end %>
       </tbody>
     </table>
     <% end %>
   </div>

   </div>

       <br><br>
       <%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/pages/manhattan.html.erb
<a href="/pages/manhattan"></a>

<div class="row">
  <div class="col-md-8">
  <input id="pac-input" class="controls" type="text" placeholder="Search Box">
  <div id="map"></div>
  <script>
    function initAutocomplete() {
      var map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: 40.748710, lng: -73.985656},
        zoom: 14,
        mapTypeId: 'roadmap'
      });


      var input = document.getElementById('pac-input');
      var searchBox = new google.maps.places.SearchBox(input);
      map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

      map.addListener('bounds_changed', function() {
        searchBox.setBounds(map.getBounds());
      });

      var markers = [];

      searchBox.addListener('places_changed', function() {
        var places = searchBox.getPlaces();

        if (places.length == 0) {
          return;
        }


        markers.forEach(function(marker) {
          marker.setMap(null);
        });
        markers = [];


        var bounds = new google.maps.LatLngBounds();
        places.forEach(function(place) {
          if (!place.geometry) {
            console.log("Returned place contains no geometry");
            return;
          }
          var icon = {
            url: place.icon,
            size: new google.maps.Size(71, 71),
            origin: new google.maps.Point(0, 0),
            anchor: new google.maps.Point(17, 34),
            scaledSize: new google.maps.Size(25, 25)
          };

          markers.push(new google.maps.Marker({
            map: map,
            icon: icon,
            title: place.name,
            position: place.geometry.location
          }));

          if (place.geometry.viewport) {

            bounds.union(place.geometry.viewport);
          } else {
            bounds.extend(place.geometry.location);
          }
        });
        map.fitBounds(bounds);
      });
    }

  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAINDFMDvbITIo5__B3SmyEGa9kgplsUGU&libraries=places&callback=initAutocomplete"
       async defer></script>
     </div>
     <div class="col-md-4">
       <mark style="background:rgba(115,163,38,0.6)!important;font-size: 24px;box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.8), 0 6px 20px 0 rgba(0, 0, 0, 0.8);margin-left: 37%">Recommended</mark>
     <% if @reviews.blank? %>
       <h3></h3>
     <% else %>
     <table class="table" style="box-shadow: 0 4px 8px 0 rgba(172, 194, 116, 0.8), 0 6px 20px 0 rgba(0, 0, 0, 0.8)">
       <tbody>
         <% @restaurants.each do |restaurant| %>
           <tr>
             <td>
               <%= restaurant.name %>
              <%= restaurant.address %>
              <%= restaurant.phone %>
             <%= restaurant.website %>
             </td>
           </tr>
         <% end %>
       </tbody>
     </table>
     <% end %>
   </div>

   </div>

       <br><br>
       <%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/pages/westchester.html.erb
<a href="/pages/westchester"></a>

<div class="row">
  <div class="col-md-8">
  <input id="pac-input" class="controls" type="text" placeholder="Search Box">
  <div id="map"></div>
  <script>
    function initAutocomplete() {
      var map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: 41.029741, lng: -73.773908},
        zoom: 14,
        mapTypeId: 'roadmap'
      });

      var input = document.getElementById('pac-input');
      var searchBox = new google.maps.places.SearchBox(input);
      map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

      map.addListener('bounds_changed', function() {
        searchBox.setBounds(map.getBounds());
      });

      var markers = [];

      searchBox.addListener('places_changed', function() {
        var places = searchBox.getPlaces();

        if (places.length == 0) {
          return;
        }


        markers.forEach(function(marker) {
          marker.setMap(null);
        });
        markers = [];


        var bounds = new google.maps.LatLngBounds();
        places.forEach(function(place) {
          if (!place.geometry) {
            console.log("Returned place contains no geometry");
            return;
          }
          var icon = {
            url: place.icon,
            size: new google.maps.Size(51, 51),
            origin: new google.maps.Point(0, 0),
            anchor: new google.maps.Point(17, 34),
            scaledSize: new google.maps.Size(25, 25)
          };

          markers.push(new google.maps.Marker({
            map: map,
            icon: icon,
            title: place.name,
            position: place.geometry.location
          }));

          if (place.geometry.viewport) {

            bounds.union(place.geometry.viewport);
          } else {
            bounds.extend(place.geometry.location);
          }
        });
        map.fitBounds(bounds);
      });
    }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAINDFMDvbITIo5__B3SmyEGa9kgplsUGU&libraries=places&callback=initAutocomplete"
       async defer></script>
     </div>
     <div class="col-md-4">
         <mark style="background:rgba(115,163,38,0.6)!important;font-size: 24px;box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.8), 0 6px 20px 0 rgba(0, 0, 0, 0.8);margin-left: 37%">Recommended</mark>
       <% if @reviews.blank? %>
         <h3></h3>
       <% else %>
       <table class="table" style="box-shadow: 0 4px 8px 0 rgba(172, 194, 116, 0.8), 0 6px 20px 0 rgba(0, 0, 0, 0.8)">
         <tbody>
           <% @restaurants.each do |restaurant| %>
             <tr>
               <td>
                 <%= restaurant.name %>
                <%= restaurant.address %>
                <%= restaurant.phone %>
               <%= restaurant.website %>
               </td>
             </tr>
           <% end %>
         </tbody>
       </table>
       <% end %>
     </div>

     </div>
<br><br>
<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant, class: "btn btn-link" %>
<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/index.html (copy).erb
<p id="notice"><%= notice %></p>

<div class ="jumbotron">
<h2>ESRT Lunch Time</h2>
<h3>Read reviews about local dining spots from your fellow co-workers and<br>
Don't forget to leave reviews and ratings for your fellow foodies.
</h3>
</div>

<div id="slideshow" class="sliders" style:"clear:both;">
  <div class="active-slide slide">
    <%= image_tag "https://s3.amazonaws.com/esrplunchtime/sliders/RyansRestaurant.jpg" %>
  </div>
  <div class="slide">
    <%= image_tag "https://s3.amazonaws.com/esrplunchtime/sliders/bar.jpg" %>
  </div>
  <div class="slide">
    <%= image_tag "https://s3.amazonaws.com/esrplunchtime/sliders/bar2.jpg" %>
  </div>
  <div class="slide">
    <%= image_tag "https://s3.amazonaws.com/esrplunchtime/sliders/chicken.jpg" %>
  </div>
  <div class="slide">
    <%= image_tag "https://s3.amazonaws.com/esrplunchtime/sliders/restaurant.jpg" %>
  </div>
</div>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
        <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= restaurant.website %></td>
        <td><%= link_to 'Show', restaurant, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= image_tag "https://s3.amazonaws.com/esrplunchtime/emp597.jpg", :class => "footer_image" %>

<script type="text/javascript">
  $(document).ready(function () {
    $("#slideshow").sliders({
        interval: 5000
      });
  });
</script>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<div class ="jumbotron">
<h2>NSP Lunch Break</h2>
<h3>Read reviews about local dining spots from your fellow co-workers and<br>
Don't forget to leave reviews and ratings for your fellow foodies.
</h3>
</div>

<div id="slideshow" class="sliders" style:"clear:both;">
  <div class="active-slide slide">
    <%= image_tag "https://s3.amazonaws.com/esrplunchtime/sliders/RyansRestaurant.jpg" %>
  </div>
  <div class="slide">
    <%= image_tag "https://s3.amazonaws.com/esrplunchtime/sliders/bar.jpg" %>
  </div>
  <div class="slide">
    <%= image_tag "https://s3.amazonaws.com/esrplunchtime/sliders/bar2.jpg" %>
  </div>
  <div class="slide">
    <%= image_tag "https://s3.amazonaws.com/esrplunchtime/sliders/chicken.jpg" %>
  </div>
  <div class="slide">
    <%= image_tag "https://s3.amazonaws.com/esrplunchtime/sliders/restaurant.jpg" %>
  </div>
</div>


<div class="container">
    <% @restaurants.each do |restaurant| %>
  <div class="row">
    <div class="[ col-xs-12 col-sm-offset-2 col-sm-8 ]">
      <ul class="event-list">
        <li>
          <img alt="Captains Cafe" src="https://s3.amazonaws.com/esrplunchtime/frontpage/captains.jpg" />
          <div class="info">
        <h2 class="title"><%= restaurant.name %></h2>
        <p class="desc"><%= restaurant.address %></p>
        <p class="desc"><%= restaurant.phone %></p>
        <p class="desc"><%= restaurant.website %></p>
      </div>
      <div class="social">
        <ul>
          <li><p class="desc"><%= link_to 'View', restaurant, class: "btn btn-link" %></p></li>
          <li><p class="desc"><%= link_to 'Map', restaurant, class: "btn btn-link" %></p></li>
          <li><p class="desc"><%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-link" %></p></li>
          <li></li>
        </ul>
      </div>
    </li>
  </ul>
</div>
</div>
    <% end %>
</div>
<br>


<%= image_tag "https://s3.amazonaws.com/esrplunchtime/emp597.jpg", :class => "footer_image" %>

<script type="text/javascript">
  $(document).ready(function () {
    $("#slideshow").sliders({
        interval: 5000
      });
  });
</script>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/search.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
        <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= link_to restaurant.website, restaurant.website %></td>
        <td><%= link_to 'Show', restaurant, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6">
    <%= image_tag @restaurant.image_url %>

    <h2>
      <%= @restaurant.name %>
    </h2>

    <div class="star-rating" data-score= <%= @avg_rating %> ></div>
    <p><%= "#{@reviews.length} reviews" %></p>

    <p>
      <strong>Address:</strong>
      <%= @restaurant.address %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @restaurant.phone %>
    </p>

    <p>
      <strong>Website:</strong>
      <%= link_to @restaurant.website, @restaurant.website %>
    </p>

    <%= link_to "Write Review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>

    <br>
    <br>
    <iframe
      width="350"
      height="350"
      frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAINDFMDvbITIo5__B3SmyEGa9kgplsUGU
        &q=<%= @restaurant.address.parameterize %>&zoom=14">
</iframe>
</div>


  <div class="col-md-6">
      <mark style="background:rgba(115,163,38,0.6)!important;font-size: 24px;box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.8), 0 6px 20px 0 rgba(0, 0, 0, 0.8);margin-left: 37%">Recent Activity</mark>
    <% if @reviews.blank? %>
      <h3>No reviews yet. Be the first to write one!</h3>
    <% else %>
    <table class="table" style="box-shadow: 0 4px 8px 0 rgba(172, 194, 116, 0.8), 0 6px 20px 0 rgba(0, 0, 0, 0.8)">
      <tbody>
        <% @reviews.each do |review| %>
          <tr>
            <td>
              <div class="star-rating" data-score= <%= review.rating %> ></div>
              <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>


<%= link_to 'Edit', edit_restaurant_path(@restaurant), class: "btn btn-link" %> |
<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

<script>
  $('.star-rating').raty({
    path: 'https://s3.amazonaws.com/esrplunchtime/stars',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>
<%= render 'form' %>
<%= link_to 'Back', restaurant_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= render 'form' %>
<%= link_to 'Back', restaurant_path(@restaurant) %>